<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-03-28T09:47:07 IST" name="Default suite" finished-at="2023-03-28T09:47:35 IST" duration-ms="27587">
    <groups>
    </groups>
    <test started-at="2023-03-28T09:47:07 IST" name="Default test" finished-at="2023-03-28T09:47:35 IST" duration-ms="27587">
      <class name="recap.CalcualtorApp">
        <test-method is-config="true" signature="setup()[pri:0, instance:recap.CalcualtorApp@68c72235]" started-at="2023-03-28T09:47:07 IST" name="setup" finished-at="2023-03-28T09:47:20 IST" duration-ms="13310" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="verifyAddTest()[pri:0, instance:recap.CalcualtorApp@68c72235]" started-at="2023-03-28T09:47:20 IST" name="verifyAddTest" finished-at="2023-03-28T09:47:28 IST" duration-ms="7554" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyAddTest -->
        <test-method signature="verifyMultTest()[pri:0, instance:recap.CalcualtorApp@68c72235]" started-at="2023-03-28T09:47:28 IST" name="verifyMultTest" finished-at="2023-03-28T09:47:34 IST" duration-ms="6637" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [1996] but found [996004]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [1996] but found [996004]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at recap.CalcualtorApp.verifyMultTest(CalcualtorApp.java:78)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyMultTest -->
      </class> <!-- recap.CalcualtorApp -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
